# Generated by Django 5.1.2 on 2025-02-08 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password_hash', models.CharField(max_length=128)),
                ('ssn', models.CharField(blank=True, max_length=11, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('filing_status', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['user_id'], name='users_user_id_83dd09_idx')],
            },
        ),
    ]
